# Test your FastAPI endpoints

GET http://localhost:8000/
Accept: application/json

###

POST http://localhost:8000/animal/dog
Accept: application/json

###

POST http://localhost:8000/image
Content-Type: application/json

{"text":  "photo of coding corgi dog in the luxury office"}